# Belajar Dasar NumPy

Berasal dari kata "Numerical Python", Numpy merupakan salah satu library pada Python yang berfungsi melakukan proses komputasi numerik. Sedangkan Array merupakan kumpulan variabel yang memiliki tipe data yang sama. Numpy menyimpan datanya dalam bentuk array. Bentuk dari numpy array adalah multidimensional yang mana dapat berupa 1-dimensi maupun 2-dimensi. Array 1-dimensi adalah sekumpulan data yang berisikan nama variabel dan tipe data yang sama yang dapat diakses menggunakan 1 buah index saja. Sedangkan array 2-dimensi adalah sekumpulan data yang berisikan nama dan tipe data yang sama dimana elemennya dapat diakses menggunakan 2 buah index yaitu index kolom dan index baris. 

In [1]:
import numpy as np

In [2]:
angka = [2, 4, 6]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([2, 4, 6])

In [5]:
angkanp * 10

array([20, 40, 60])

In [6]:
angka * 3

[2, 4, 6, 2, 4, 6, 2, 4, 6]

In [7]:
print(angkanp)

[2 4 6]


In [8]:
versiList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
versiList

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
versiNp = np.array(versiList)
versiNp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 100, 2, int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [28]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((2, 2), int)

array([[1, 1],
       [1, 1]])

In [38]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

# Matrix Identity

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])