In [1]:
import numpy as np

In [2]:
# Bilangan Distribusi Uniform (0 - 1)

np.random.rand(10)

array([0.08793099, 0.71143513, 0.77431747, 0.01591664, 0.168952  ,
       0.58879261, 0.76215572, 0.74674286, 0.02928774, 0.1636607 ])

In [3]:
# Bilangan Distribusi Uniform (0 - 1) Matrix 2D

np.random.rand(5, 4)

array([[0.65158975, 0.54117874, 0.9893744 , 0.27588051],
       [0.43594197, 0.2255785 , 0.64053886, 0.24923081],
       [0.79302874, 0.48140343, 0.09578168, 0.35571476],
       [0.84752755, 0.90029974, 0.2720843 , 0.21660594],
       [0.22887133, 0.30728187, 0.00594148, 0.45981938]])

In [4]:
# Distribusi Normal (Gaussian)

np.random.randn(2, 2)

array([[-0.04103562,  0.40389317],
       [-0.91380903,  1.08961575]])

In [5]:
from numpy.random import randn, randint

In [6]:
randn(2, 4)

array([[-0.56199771, -1.6114264 , -0.32944036, -1.36647088],
       [-0.37409998, -0.67307113, -0.66539686,  0.41551505]])

In [7]:
randint(0, 10, 5)

array([9, 9, 3, 4, 2])

In [8]:
dataBil = randint(0, 100, 20)

In [9]:
print(dataBil)

[48 82 15 59 47 95 80 41 68 20 29 10 51 51 16 81 36 50 89 20]


In [10]:
print(dataBil)

[48 82 15 59 47 95 80 41 68 20 29 10 51 51 16 81 36 50 89 20]


In [11]:
dataBil.reshape(4, 5)

array([[48, 82, 15, 59, 47],
       [95, 80, 41, 68, 20],
       [29, 10, 51, 51, 16],
       [81, 36, 50, 89, 20]])

In [12]:
dataBil.sort()

In [13]:
dataBil

array([10, 15, 16, 20, 20, 29, 36, 41, 47, 48, 50, 51, 51, 59, 68, 80, 81,
       82, 89, 95])

In [14]:
dataBil.reshape(4, 5)

array([[10, 15, 16, 20, 20],
       [29, 36, 41, 47, 48],
       [50, 51, 51, 59, 68],
       [80, 81, 82, 89, 95]])

In [15]:
dataBil

array([10, 15, 16, 20, 20, 29, 36, 41, 47, 48, 50, 51, 51, 59, 68, 80, 81,
       82, 89, 95])

In [16]:
dataBil = dataBil.reshape(4, 5)

In [17]:
dataBil

array([[10, 15, 16, 20, 20],
       [29, 36, 41, 47, 48],
       [50, 51, 51, 59, 68],
       [80, 81, 82, 89, 95]])

In [18]:
dataBil.max()

95

In [19]:
data2D = randint(0,10,10).reshape(2, 5)

In [20]:
data2D

array([[0, 3, 6, 6, 8],
       [0, 9, 9, 9, 1]])

In [21]:
data2D.max()

9

In [22]:
data2D.argmax()

6

In [23]:
data2D.argmin()

0

In [24]:
data2D.shape

(2, 5)

In [25]:
data2D.dtype

dtype('int32')

# Indexing di NumPy

In [26]:
import numpy as np

In [27]:
coba = np.arange(0, 11)

In [28]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
coba[5:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
coba[5:9]

array([5, 6, 7, 8])

In [31]:
coba[:6]

array([0, 1, 2, 3, 4, 5])

In [32]:
coba3 = coba[5:]
coba3

array([ 5,  6,  7,  8,  9, 10])

In [33]:
coba3[2:] = 99
coba3

array([ 5,  6, 99, 99, 99, 99])

In [34]:
coba

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99])

In [35]:
coba3

array([ 5,  6, 99, 99, 99, 99])

### Keunian NumPy

Variable Coba2 tidak berdiri sendiri, namun seperti cerminan dari variable coba. Jadi, jika kita melakukan sesuatu di coba2 maka variable coba akan terdampak. Namun, ada solusi supaya tidak seperti ini

In [36]:
coba2 = coba.copy()

In [37]:
coba2

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99])

In [38]:
coba2[0:] = 100

In [39]:
coba2

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [40]:
coba

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99])

In [41]:
bil2D = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

bil2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
bil2D[0]

array([1, 2, 3])

In [43]:
bil2D[0][1]

2

### Penulisan di atas kurang "Pythonic"

Alih-alih menggunakan bil2D[n][m], kita bisa menggunakan bil2D[n, m]

In [44]:
bil2D[2,2]

9

In [45]:
bil2D[0, 1]

2

In [46]:
bil2D[1,1:]

array([5, 6])

## Slicing dengan Boolean di NumPy

In [47]:
bilBaru = np.arange(0, 11)

In [48]:
bilBaru

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
angkaT = bilBaru > 5

In [50]:
angkaT

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [51]:
bilNew = bilBaru[angkaT]

In [52]:
print(bilNew)

[ 6  7  8  9 10]


In [53]:
bilBaru = bilBaru[bilBaru % 2 == 0]

In [54]:
bilBaru

array([ 0,  2,  4,  6,  8, 10])